# docker-compose.yml
version: '3.8'
services:
  dbt:
    image: fishtownanalytics/dbt:1.0.0
    volumes:
      - ./dbt:/usr/app/dbt
    environment:
      DBT_PROFILES_DIR: ${DBT_PROFILES_DIR}
    command: dbt run
    depends_on:
      - clickhouse-server

  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.6
    container_name: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    network_mode: host
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE

  clickhouse-init:
    image: clickhouse/clickhouse-client
    command: ["clickhouse-client", "--multiquery", "--host=clickhouse-server", "--query=select 1"]
    depends_on:
      - clickhouse-server


    